nelmio_api_doc:
    documentation:
        info:
            title: Billing.Study-On
            description: Login and Register for Study-On
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1/auth
            - ^/api/v1/register

