nelmio_api_doc:
    documentation:
        info:
            title: Billing.Study-On
            description: Login and Register for Study-On
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: "Authorization: Bearer {token}"
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1/auth
            - ^/api/v1/register
            - ^/api/v1/users/current
            - ^/api/v1/token/refresh
            - ^/api/v1/courses/{code}/pay
            - ^/api/v1/courses
            - ^/api/v1/courses/{code}
            - ^/api/v1/transactions

