security:
    encoders:
        App\Entity\BillingUser:
            algorithm: argon2i

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\BillingUser
                property: email
    firewalls:
        login:
            pattern: ^/api/v1/auth
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/v1/auth
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern: ^/api/v1/register
            stateless: true
            anonymous: true
        course_pay:
            pattern: ^/api/v1/courses/(.+)/pay
            stateless: true
            anonymous: false
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        courses:
            pattern: ^/api/v1/courses
            stateless: true
            anonymous: true
        refresh:
            pattern: ^/api/v1/token/refresh
            stateless: true
            anonymous: true
        doc:
            pattern: ^/api/v1/doc
            stateless: true
            anonymous: true
        current_user:
            pattern: ^/api/v1/users/current
            stateless: true
            anonymous: false
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        transactions:
            pattern: ^/api/v1/transactions
            stateless: true
            anonymous: false
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/current_user, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/course_pay, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/transactions, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/courses, roles: IS_AUTHENTICATED_ANONYMOUSLY }